ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
  USEMODULE += gnrc_netdev2
  ifeq (,$(filter gnrc_tisch,$(USEMODULE)))
    USEMODULE += gnrc_nomac
  endif
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
